(define (pascal row col)
  (if (> col row)
      (error "invalid")
      (if (or (= 0 col) (= col row))
          1
          (+ (pascal (- row 1) (- col 1))
             (pascal (- row 1) col)))))

(display (pascal 5 0))
(newline)
(display (pascal 5 1))
(newline)
(display (pascal 5 2))
(newline)
(display (pascal 5 3))
(newline)
(display (pascal 5 4))
(newline)
(display (pascal 5 5))
(newline)
(display (pascal 5 6))
(newline)
(exit)